# Generated by Django 4.2.23 on 2025-09-02 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('file', models.ImageField(upload_to='templates/')),
                ('course', models.CharField(max_length=120)),
                ('template_type', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('hallticket', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('course', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('last_certificate', models.FileField(blank=True, upload_to='certificates/')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.template')),
            ],
        ),
        migrations.CreateModel(
            name='SendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR')], max_length=10)),
                ('error_reason', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('attachment', models.FileField(blank=True, upload_to='sent_attachments/')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.student')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.template')),
            ],
        ),
    ]
