# Generated by Django 4.2.23 on 2025-09-03 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_student_options_student_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hallticket', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('hallticket', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('message', models.TextField(default='Processed successfully')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
